seed: 42
overfit_batch: null
logs: false
patience: 3
logdir: lightning_logs
experiment_name: CI_full_sentence
experiment_version: no_shared/freeze_bert_1e5
eval_period_epochs: 1
max_train_epochs: 200
disable_checkpoints: true
learning_rate: 1.0e-05
freeze_embedder: true
