seed: 42
overfit_batch: null
logs: false
patience: 100
logdir: lightning_logs
experiment_name: CI_CC_token
experiment_version: freeze_bert_1e4_patient_bert
eval_period_epochs: 1
max_train_epochs: 200
disable_checkpoints: true
learning_rate: 0.0001
freeze_embedder: true
