seed: 42
learning_rate: 5.0e-05
overfit_batch: true
logs: false
patience: 500
logdir: lightning_logs
experiment_name: CI_full_sentence
experiment_version: overfit_batch_no_shared/5e5
eval_period_epochs: 50
max_train_epochs: 500
